name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.6.1
        virtualenvs-create: false
        virtualenvs-in-project: false
        virtualenvs-path: ~/myvenv
        installer-parallel: true

    - name: Install python dependencies
      run: poetry install

    - name: Run tests
      run: make unittests